Repository kollavarsham/calendar-vue, pull requests merged in 2021-05, with the labels that each got.

#14 [UPDATED] Add Footer & banner
  babel.config.js
  package-lock.json
  package.json
  public/index.html
  src/App.vue
  src/assets/underconstruction.png
  src/components/Calendar.vue
  src/components/Footer.vue
  src/components/HelloWorld.vue
  src/main.js
  src/plugins/bootstrap-vue.js
Labels: ui

#21 Add issue template
  .github/ISSUES_TEMPLATE/bug_report.md
Labels: documentation

#22 Add PR Template
  .github/pull_request_template.md
Labels: documentation

#18 update dependencies - closes #17
  package-lock.json
  package.json
Labels: dependencies
